### PR TITLE
Etl

### PR DESCRIPTION
**Pull request by lfunderburk**

### CODE REVIEW

**Comment by lfunderburk** [comment]
Hi @btmarsh6 
See you built a document store and an app

is it working as expected?

**Comment by btmarsh6** [comment]
Hi @lfunderburk unfortunately I'm not able to get it working. The step to update the embeddings for the document store takes a very long time on my computer since I don't have  GPU. I think my kernel crashes before it successfully completes.

**Comment by lfunderburk** [comment]
Understand. In this case can you explore an in memory document store with the BM25 retriever? https://github.com/lfunderburk/llmops-with-haystack/blob/main/first-rag-bot/chainlit-app/README.md

**Comment by lfunderburk** [comment]
Merging into develop
Next goal is to clean up redundant scripts and consolidate your work with Eva's

**Pull request merged**
